version: '1'
services:
  banco:
    container_name: banco
    image: DockerImagen/banco:1
    build: ./postgres
    ports:
      - "5433:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  app:
    container_name: app
    image: DockerImagen/app:1
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - banco
    links:
      - "banco:host-banco"
volumes:
  dbdata:
    driver: local